#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from argparse import ArgumentParser
import json

with open("config.json") as conFile:
    data = json.load(conFile)

Config = data[0]
Interpreters = data[1]
Languages = data[2]

outputLanguage = Config["defaultLanguage"]
sentences = Languages[outputLanguage]

parser = ArgumentParser(description = sentences["description"])
parser.add_argument("file", metavar=sentences["file"], type=str, help=sentences["scriptname"])
parser.add_argument("interpreter", metavar="Interpreter", type=str, help=sentences["interpreter"])
parser.add_argument("-e", "--executable", default = Config["executable"], help=sentences["executable"])
parser.add_argument("-v", "--version", action="version", version="0.94", help=sentences["version"])
args = parser.parse_args()
    
Ip = args.interpreter
if Ip in Interpreters:
    Shebang = Interpreters[Ip]
else:
    if Config["notifications"]:        
        permission = input(sentences["unknownInterpreter"]+ "[y/n]")
        if permission == "y":
            Shebang = ''.join(["#!", Ip])
        else:
            print(sentences["abort"])
            quit()
    else:
        Shebang = ''.join(["#!", Ip])

try:
    with open(args.file, "r+") as script:
        content = script.readlines()
        script.seek(0,0)
        firstLineLst = list(content[0])
        if firstLineLst[0] == "#" and firstLineLst[1] == "!":
            del(content[0])
        script.write(Shebang+ "\n"+ "".join(content))
except FileNotFoundError:
    print(sentences["fileError"])

if args.executable == "True":
    from os import system
    system("chmod +x "+ args.file)
